server:
  port: 3000
spring:
  datasource:
    username: root
    password: Lzx12345
    url: jdbc:mysql://localhost:3306/bms?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    cache: true
    suffix: .html
    encoding: UTF-8
    content-type: text/html
    mode: HTML
  security:
    user:
      name: lzx
      password: Lzx12345
      roles: admin
  redis:
    host: localhost
    port: 6379
  cache:
    type: redis
    redis:
      use-key-prefix: true
      key-prefix: sms_
      cache-null-values: false
      time-to-live: 10s
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

